<?php

class HomeController extends Controller
{
    public function actions()
    {
        return parent::actions(); // TODO: Change the autogenerated stub
    }

    public function __construct($id, $module = null)
    {
        parent::__construct($id, $module);
        $this->checkDomain($id);

    }

    public function actionIndex()
    {
        $data = [
            ["id" => 1, "name" => 'Tom',]
        ];
        $this->render('index', ['data' => $data]);

    }

    public function actionHello()
    {
        return "hello thanhrain";
    }
}